sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t shwetalishine/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shwetalishine/docker-react npm run test
